/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ListaDeExerciciosPOO;

public class App {

    public static void main(String[] args) {
        
        Invoice inv = new Invoice(1, "Moudepad", 10, 50.0f);
        
        System.out.println("Valor total: " + inv.getInvoiceAmount());

    }
}
