Algoritmo "Escolha"
// Descrição   : Testes
// Autor(a)    : Jeffrey
// Data atual  : 15/03/2022
Var
   voto: caractere
   
Inicio

Escreval ("Digite seu voto")
leia(voto)

Escolha voto
caso "20"
     Escreval("Você votou em Marcelo Bernart")
caso "30"
     Escreval("Você votou no Pernalonga")
caso "40"
     Escreval("Você votou no Patolino")
outrocaso
     Escreval("Voto nulo")
fimescolha
Fimalgoritmo