Algoritmo "Para III"
// Descrição   : Testes
// Autor(a)    : Jeffrey
// Data atual  : 15/03/2022
Var
i, aleatorioMaximo,aleatorioMinimo,incremento: inteiro
Inicio

repita
aleatorio 1,100
  leia(aleatorioMaximo)
  leia(aleatorioMinimo)
aleatorio off
ate aleatorioMaximo >= aleatorioMinimo
limpatela

aleatorio 1,5
leia(incremento)
aleatorio off
limpatela

para i de aleatorioMinimo ate aleatorioMaximo passo incremento faca
  escreval(i)
fimpara

Fimalgoritmo