Algoritmo "Trabalhando com tipos"
// Descrição   : Testes
// Autor(a)    : Jeffrey
// Data atual  : 15/03/2022
Var
      palavra1, palavra2, palavra3: caractere
      numero1, numero2, numero3: inteiro
Inicio
      Escreval("Palavra 1: ")
      leia(palavra1)
      Escreval("Palavra 2: ")
      leia(palavra2)
      Escreval("Numero 1: ")
      leia(numero1)
      Escreval("Numero 2: ")
      leia(numero2)
      palavra3 <- palavra1 + palavra2
      numero3 <- numero1 + numero2
      Escreval("")
      Escreval(palavra3)
      Escreval(numero3)
Fimalgoritmo